# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nijes
email: abergerb@gmail.com
description: > # this means to ignore newlines until "baseurl:"

Having owned a camera for over 8 years, my enthusiasm for capturing
and creating memorable stories keeps growing.
Providing me with good baggage and partnerships .
With this perspective in mind i have both managed and produced products
in multiple fields: SAS (Gaming), FinTech, Social Network platform, Music, and more.
All of which were excellent efforts, that have lead me to seek a grater volume of work that will further have me going.
I look forward to helping you, sounds harsh...i am HERE

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
# Build settings
markdown: kramdown
